server:
  port: 8083
  servlet:
    context-path: /example

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.97.185.196:3306/aliyunDB?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
      #开启内容商议，返回的内容格式可以更改
    contentnegotiation:
      favor-parameter: true

knife4j:
  enable: true


#notification:
#  service: email

notification:
    service: sms




